package Interface;

import Classes.Bebida;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;


public class menu_bebida extends javax.swing.JInternalFrame {
    
    private List<Bebida> listaBebidas;
    
  
    public menu_bebida() {
        initComponents();
        listaBebidas = new ArrayList<>();
        
         txt_codBebi.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            txt_nomeBebi.requestFocusInWindow(); 
        }
    });
   
    txt_nomeBebi.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            txt_litros.requestFocusInWindow();
        }
    });

    txt_litros.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            txt_precoVenda.requestFocusInWindow(); 
        }
    });

    txt_precoVenda.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            txt_quant.requestFocusInWindow(); 
        }
    });

    txt_quant.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            txt_teor.requestFocusInWindow();
        }
    });

    txt_teor.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            jButton1.doClick();
        }
    });

    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_codBebi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nomeBebi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_litros = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_quant = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_teor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_precoVenda = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro bebida");

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        jLabel3.setText("ML:");

        jLabel4.setText("Quantidade:");

        jLabel5.setText("Teor Alcoólico:");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Preço:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_quant, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_codBebi)
                                    .addComponent(txt_nomeBebi)
                                    .addComponent(txt_litros, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                                .addComponent(txt_precoVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_teor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_codBebi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_nomeBebi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txt_litros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(19, 19, 19)
                .addComponent(txt_precoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txt_quant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(txt_teor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean verificaCodigo(String cod) {
        
        for (Bebida bebida : listaBebidas) {
            if (bebida.getCodigo().equals(cod)) {
                return true;
            }
        }
        return false;
}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        try{

        String codigo = (txt_codBebi.getText());
        
        if (verificaCodigo(codigo)) {
            JOptionPane.showMessageDialog(this, "O código do cliente já existe. Por favor, digite novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
            txt_codBebi.setText("");
            return;
        }

        String nome = txt_nomeBebi.getText();
        int conteudoLiquido = Integer.parseInt(txt_litros.getText());
        double precoVenda = Double.parseDouble(txt_precoVenda.getText());
        int quantidadeEstoque = Integer.parseInt(txt_quant.getText());
        double teorAlcoolico = Double.parseDouble(txt_teor.getText());

        Bebida bebida = new Bebida(codigo, nome, conteudoLiquido, precoVenda, quantidadeEstoque, teorAlcoolico);


        listaBebidas.add(bebida);


        JOptionPane.showMessageDialog(this, "Bebida cadastrada com sucesso!");


        txt_codBebi.setText("");
        txt_nomeBebi.setText("");
        txt_litros.setText("");
        txt_precoVenda.setText("");
        txt_quant.setText("");
        txt_teor.setText("");
        txt_codBebi.requestFocus();
        
        tela_inicial telaInicial = (tela_inicial) getTopLevelAncestor();
        telaInicial.atualizarTabelaBebidas(listaBebidas);

        }catch (NumberFormatException e) {

                JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos corretamente.", "Erro", JOptionPane.ERROR_MESSAGE);
                txt_codBebi.setText("");
                txt_nomeBebi.setText("");
                txt_litros.setText("");
                txt_precoVenda.setText("");
                txt_quant.setText("");
                txt_teor.setText("");
                txt_codBebi.requestFocus();
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_codBebi;
    private javax.swing.JTextField txt_litros;
    private javax.swing.JTextField txt_nomeBebi;
    private javax.swing.JTextField txt_precoVenda;
    private javax.swing.JTextField txt_quant;
    private javax.swing.JTextField txt_teor;
    // End of variables declaration//GEN-END:variables

    public List<Bebida> getListaBebidas() {
        return listaBebidas;
    }
    
}
